### ISSUE TITLE
go get can not work in go version go1.13 darwin/amd64

### ISSUE THREAD

**Issue by yhyddr** [emitter-io/emitter#301]
## Problem
```shell 
# github.com/emitter-io/emitter/config
go/pkg/mod/github.com/emitter-io/emitter@v2.0.437+incompatible/config/config.go:66:14: undefined: config.VaultConfig
```
## environment
```shell
 go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/abser/Library/Caches/go-build"
GOENV="/Users/abser/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/abser/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/m0/q27qpd7x3r14p94qxs73k7mw0000gn/T/go-build078196314=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
## Complete log
```shell
ArideMacBook-Air:~ abser$ go get -u github.com/emitter-io/emitter && emitter
go: finding github.com/emitter-io/emitter v2.0.437+incompatible
go: downloading github.com/emitter-io/emitter v2.0.437+incompatible
go: extracting github.com/emitter-io/emitter v2.0.437+incompatible
go: finding github.com/emitter-io/config v1.0.0
go: downloading github.com/emitter-io/config v1.0.0
go: finding github.com/hashicorp/go-sockaddr v1.0.2
go: finding golang.org/x/crypto latest
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: finding github.com/karlseguin/ccache v2.0.3+incompatible
go: finding github.com/weaveworks/mesh latest
go: finding github.com/axiomhq/hyperloglog latest
go: finding github.com/kelindar/tcp v1.0.0
go: extracting github.com/emitter-io/config v1.0.0
go: downloading github.com/karlseguin/ccache v2.0.3+incompatible
go: downloading github.com/kelindar/tcp v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20200109152110-61a87790db17
go: extracting github.com/kelindar/tcp v1.0.0
go: extracting github.com/hashicorp/go-sockaddr v1.0.2
go: finding github.com/kelindar/binary v1.0.8
go: downloading github.com/weaveworks/mesh v0.0.0-20191105120815-58dbcc3e8e63
go: downloading github.com/axiomhq/hyperloglog v0.0.0-20191112132149-a4c4c47bc57f
go: extracting github.com/karlseguin/ccache v2.0.3+incompatible
go: downloading github.com/kelindar/binary v1.0.8
go: finding github.com/kelindar/process latest
go: finding github.com/valyala/fasthttp v1.7.1
go: downloading github.com/valyala/fasthttp v1.7.1
go: extracting github.com/axiomhq/hyperloglog v0.0.0-20191112132149-a4c4c47bc57f
go: extracting github.com/weaveworks/mesh v0.0.0-20191105120815-58dbcc3e8e63
go: downloading github.com/kelindar/process v0.0.0-20170730150328-69a29e249ec3
go: extracting github.com/kelindar/binary v1.0.8
go: extracting golang.org/x/crypto v0.0.0-20200109152110-61a87790db17
go: extracting github.com/kelindar/process v0.0.0-20170730150328-69a29e249ec3
go: extracting github.com/valyala/fasthttp v1.7.1
go: downloading github.com/dgryski/go-metro v0.0.0-20180109044635-280f6062b5bc
go: downloading github.com/stretchr/objx v0.1.0
go: extracting github.com/dgryski/go-metro v0.0.0-20180109044635-280f6062b5bc
go: extracting github.com/stretchr/objx v0.1.0
go: downloading github.com/klauspost/compress v1.8.2
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: extracting github.com/valyala/bytebufferpool v1.0.0
go: extracting golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: extracting github.com/klauspost/compress v1.8.2
go: downloading github.com/klauspost/cpuid v1.2.1
go: extracting github.com/klauspost/cpuid v1.2.1
go: finding github.com/klauspost/compress v1.9.7
go: finding github.com/klauspost/cpuid v1.2.2
go: finding github.com/davecgh/go-spew v0.0.0-20180830191138-d8f796af33cc
go: finding github.com/dgryski/go-metro latest
go: finding gopkg.in/yaml.v2 v2.2.7
go: finding golang.org/x/net latest
go: finding github.com/valyala/bytebufferpool v1.0.0
go: finding golang.org/x/sys latest
go: downloading golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: downloading gopkg.in/yaml.v2 v2.2.7
go: downloading golang.org/x/sys v0.0.0-20200107162124-548cf772de50
go: downloading github.com/klauspost/compress v1.9.7
go: extracting gopkg.in/yaml.v2 v2.2.7
go: extracting golang.org/x/net v0.0.0-20191209160850-c0dbc17a3553
go: extracting golang.org/x/sys v0.0.0-20200107162124-548cf772de50
go: extracting github.com/klauspost/compress v1.9.7
# github.com/emitter-io/emitter/config
go/pkg/mod/github.com/emitter-io/emitter@v2.0.437+incompatible/config/config.go:66:14: undefined: config.VaultConfig
```

**Comment by log225** [comment]
mark, the same ```go version go1.12.4 darwin/amd64```
